### PR TITLE
Js

### PR DESCRIPTION
**Pull request by edgarcosta**
- marked almost all the javascript with "defer", so it gets downloaded in parallel
- replaced `$(document).ready(function() {` with `document.addEventListener("DOMContentLoaded", function() {`, so that we don't depend on jquery at the top level, and jquery can be loaded with defer.
- moved jquery dependent code inside `document.addEventListener("DOMContentLoaded", function() {`
- fixed a bug in `edit_talk.html`
- got rid of a bunch of old javascript from lmfdb that we dont'use, for example markup code that comes from editing knowls on lmfdb

### CODE REVIEW

**Comment by edgarcosta** [comment]
I'm merging this, but in case something goes wrong, here are the script lines that we no longer load:
`edit_talk.html`:
```
<script type="text/javascript"
        src="https://cdn.jsdelivr.net/gh/markitup/1.x@1.1.15/markitup/jquery.markitup.js"
        integrity="sha256-BiawY8kuGhVgPmV3XSWamEheAvBvH9VeZbzR16BdvAM="
        crossorigin="anonymous"></script>
{# depends on color #}
<link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='markitup.css')}}" />
{# settings for the editor menus and the stylesheet #}
<script type="text/javascript" src="{{ url_for('static', filename='jquery.markitup.markdown.js')}}"></script>
<link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='markdown.css')}}" />
```

and in `base.html`:
```
<script type="text/javascript" src="{{ url_for('static', filename='jquery.watermark.min.js') }}"></script>
<script type="text/javascript" src="{{ url_for('static', filename='jquery.markitup.markdown.js') }}"></script>
<script type="text/javascript" src="{{ url_for('static', filename='showdown.min.js') }}"></script>
<script type="text/javascript" src="{{ url_for('static', filename='jquery.dataTables.js') }}"></script>
<script type="text/javascript" src="{{ url_for('static', filename='jquery.dataTables.plugins.js') }}"></script>
<script type="text/javascript" src="{{ url_for('static', filename='jquery.markitup.markdown.js') }}"></script>
```

**Comment by AndrewVSutherland** [comment]
@edgarcosta When you save a talk that has been modified it now warns about leaving the page, I'm guessing this is do to changes in this PR.

**Comment by edgarcosta** [comment]
Looking into it.

**Comment by edgarcosta** [comment]
should be fixed

**Comment by AndrewVSutherland** [comment]
Looks good, should we push to live?

**Comment by edgarcosta** [comment]
Sounds good to me

**Pull request merged**
