### PR TITLE
Support seminars with multiple talks per week

### PR DESCRIPTION
**Pull request by AndrewVSutherland**
This needs to be tested carefully before merging, a lot has changed.  I'm submitting the PR so David and Edgar can review it for any obvious problems.  I'll test it more tomorrow.

### CODE REVIEW

**Comment by AndrewVSutherland** [comment]
A few notes:
- I removed the option to change frequency and talks per day on the schedule page.  We could add the UI that lets you edit time slots from the Edit properties page to the Edit schedule page, but if so we should wait to do that in a separate PR
- Seminar series times are no longer stored as offsets from 1/1/2020, they are now simply stored as strings hh:mm-hh:mm in the column time_slots
- See convert_time_to_times for how old data is handled -- if weekday, start_time, end_time are set and weekdays and time_slots are not, it will set weekdays and time_slots to lists of length 1 using the existing parameters (and from then on ignore start_time, end_time, weekday for that series).  If we edit series on master using this code, changes to weekdays and time_slots should have no effect on the live system (but will once the code is pushed to live).
- existing frequencies are converted to 0,7,14,21 on load by convert_time_to_times (but will only be updated if the seminar is saved).  We can add more frequencies later if we wish (e.g. use -1,-2,-3,-4 for the first/second/third/fourth week of the month -- note that the user never sees a numeric frequency any more, so we can assign whatever meanings we want.
- The start_times and end_times columns can be dropped now.  Eventually we can also drop the start_time, end_time, and weekday columns, but not until all the data has been converted (which basically means loading and saving every seminar, but we should really go through them and look for seminars that meet more than once a week and set the weekdays and time_slots properly -- we should do this soon -- more data is being added every day).
- per_day is now only relevant to conferences it is not used for seminar_series.  Similarly, frequency has meaning only for seminar_series, not conferences.
- I fixed a bug in the existing schedule -- if you set the begin end times to include dates outside the current year it will create slots with dates that have no year specified and when you save will put them in the current year.  It now switches to dd-mmm-yyyy format for dates not in the current year.

**Comment by AndrewVSutherland** [comment]
I'm going to fix a few bugs I found and resubmit.

**Comment by AndrewVSutherland** [comment]
There was a typo in the code converting old start time and end time, fixed.

**Comment by roed314** [comment]
For seminars that meet biweekly, I don't see a good way to control which of the two possible every-other-week slots are shown.  Changing the start date doesn't affect it, and adding a talk to the other possibility doesn't affect it.

**Comment by AndrewVSutherland** [comment]
It tries to infer this from existing talks, not the start date, unless there are no existing talks.

First it looks for the earliest talk in the future, and if none, the latest talk in the past. 

Is it not doing that for you?

**Comment by AndrewVSutherland** [comment]
The from/to dates are only viewed as specifying a window, not saying anything about when talks should be scheduled.

**Comment by roed314** [comment]
Look at http://localhost:37778/edit/schedule/?shortname=TheTest.  I added a talk on May 5, but the slots are on May 12, May 26....

**Comment by AndrewVSutherland** [comment]
This is a bug, let me fix it (I also found one other minor issue).

**Comment by AndrewVSutherland** [comment]
@roed314 I fixed the problem you noticed (and a spurious warning for conferences).  Let me know if you spot anything else.

**Comment by roed314** [comment]
Great.  I'm going to head outside so I won't be able to look this afternoon, but I think it's in pretty good shape.  If you'd like to merge into master so that you can get more people looking at it, that's fine with me.

**Comment by AndrewVSutherland** [comment]
Thanks @roed314. I'm going to bang on it for another 15-30 minutes and if I don't find any other problems I will merge it.

**Comment by AndrewVSutherland** [comment]
OK, I cannot seem to break it (of course that doesn't mean there are no bugs).

One thing I noticed is that if you make the start and end time equal it interprets this to mean a 24 hour talk (and warns you it is longer than 8 hours).  Given that at zero-length talk isn't really a physical possibility but a 24 hour talk is at least in principle possible, I think this is reasonable, but I'm happy to change it if others disagree :)

One other detail worth noting: if the start and end times of a talk do not exactly match the regularly scheduled times of the seminar, on the schedule a slot for the regular time will still appear, even in cases where it is probably not relevant (e.g. the talk is taking place a half hour later than usual).

I could prevent unused slots that overlap scheduled talks from appearing, but the existing behavior is nice in that it correctly handles situations where there might well be overlapping talks, or even two talks with exactly the same start and end times in a series (usually this only applies to conferences but I think we should allow this for any series -- maybe I want to put dueling speakers at opposite ends of the room and see who attracts the better audience :)  In any case the Edit properties page will let you create multiple overlapping or even identical time slots, and the schedule page should cope with this)

**Pull request merged**
