### PR TITLE
improvements to talk display

### PR DESCRIPTION
**Pull request by jamiesully**

### CODE REVIEW

**Comment by roed314** [comment]
@jamiesully, Bjorn mentioned that you'd made some additional changes to this based on feedback from him and Edgar.  Let me know when you're ready for this to be merged.

**Comment by roed314** [comment]
Got it.  @edgarcosta or I will take a look this evening.  Thanks!

**Comment by edgarcosta** [comment]
It looks good.
I have some minor comments, that I would like to hear what others think about before making incorporating these changes.
1- The "Livestream access" link.
Screen Shot 2020-04-29 at 22 57 22
Do we really want the text bold and to make it look like a red button?
If we keep this style, then we should fix the "a:hover", as it looks quite bad:
Screen Shot 2020-04-29 at 22 58 53


2- Width of the talk knowl. At the moment is set to 70%. It looks a bit odd:
Screen Shot 2020-04-29 at 23 02 20

Should we center the content?
Screen Shot 2020-04-29 at 23 03 00

or try to make the knowl smaller?
Screen Shot 2020-04-29 at 23 04 05

or just do not set a max width? (I prefer this one)
Screen Shot 2020-04-29 at 23 05 10

**Comment by jamiesully** [comment]
1) I agree, the hover looks bad and should be changed if the button is red. 

Do you think the big red button is too loud? We could try something more muted, but still easy to spot. 

2) I prefer the 100% width as well. Was there some rational for setting it to 70% originally?

**Comment by roed314** [comment]
I think I like the big red button, since when someone want the livestream they are often in a hurry and will appreciate the color.

100% width looks good to me.  I think the 70% is getting carried over from somewhere else.

**Comment by AndrewVSutherland** [comment]
Not a fan of the big red button unless we only show this for talks that are actually live right now (or maybe scheduled to start in the next 5-10 minutes).  Otherwise it is confusing (is a Zoom meeting that doesn't start for two weeks really a "livestream"?) and way too loud.  If I see a big red button screaming at me to click it I expect something exciting will happen when I do.  Being taken to a waiting room for a meeting that isn't scheduled to start for days is not exciting.

**Comment by jamiesully** [comment]
I made the 'big red button' with the use-case in mind of a user looking to watch the talk 2 min before it begins. So I think the idea of making it turn red  5-15 min before a talk begins is sensible. 

I would still make it prominent at all times, though, because I think it should be made clear to newer users where they will eventually need to click to launch the livestream when the time comes. 

Perhaps still a big button, but leave the background black until just before?

**Comment by edgarcosta** [comment]
Jamie, I find it weird to see a button there.
Usually, a button means an action, while this is honestly a link.

**Comment by jamiesully** [comment]
I tend to think of 'launch the livestream' as an action (especially as it tends to open up the Zoom app most of the time), but I don't have strong feelings about the exact style of the link. My only concern is making where to go to see the talks as obvious as possible for users.

**Comment by jamiesully** [comment]
I know we may not like the buttons, but here is what the different options look like depending on time/link availability:

image

**Comment by roed314** [comment]
What about only displaying as a button if it's ongoing or within the next 10 minutes?
Screen Shot 2020-04-30 at 1 45 48 PM
Screen Shot 2020-04-30 at 1 46 25 PM

**Comment by AndrewVSutherland** [comment]
It would be nice if there was a way to tell if a password or registration is required and note this right next to the button.  I worry about people being frustrated if they click the button but cannot get in.  If we are going to show a big red button we really want to be as sure as we can that it will work.

Is it possible to determine (programatically) whether a zoom link is password protected or not?

**Comment by roed314** [comment]
I just looked a bit and I don't see a way to do it.  We could search the seminar/talk comments for "password" or "register"....

**Comment by jamiesully** [comment]
I think the best way to deal with passwords is to explicitly collect that information?

At risk of driving everyone mad, here is one more iteration on David's suggestion. I've kept the 'livestream access' boxed to draw attention to it, but not made it look like a button unless the talk is about to start.

image

**Comment by AndrewVSutherland** [comment]
@jamiesully I'm worried about the situation where the organizer forgets to indicate that a password is required and explain how to get it -- if there were an automated way to detect this it would be a big help.  But it might also be a good idea to a check box the organizer is supposed to click to indicate if password or registration is required (currently they are instructed to just explain this in the comments).

**Comment by roed314** [comment]
I've created #327 for ideas on improving our presentation of Zoom passwords and registration requirements.  But I don't think this PR should wait on fixing that.

**Comment by roed314** [comment]
@jamiesully I'm happy to merge this if you include my recent changes.  I can also combine them as well if you push your most recent code.

**Comment by AndrewVSutherland** [comment]
@roed314 Agreed, it would be good to get an updated version merged to master so that Bjorn can take look at it.  We can make further tweaks there before pushing to live if needed.

**Comment by roed314** [comment]
I made some further edits.  @jamiesully, if there are any that you disagree with we can talk further tomorrow.  The results are now viewable on https://master.mathseminars.org and https://master.researchseminars.org

**Pull request merged**
